Added python version for function examples
HowProgrammingWorks/Function pull request #1
Opened 2017-04-05 16:31 UTC by AndreyBar

I rewrote examples of functions in Python 3.  Not every piece of code could be rewritten because of Python possibilities.

2017-04-06 17:39 UTC, tshemsedinov approved these changes

2017-06-06 23:08 UTC, aqrln commented on Python/7-method.py
> +Methods examples.
That's not true. The functions in this example are just functions. And that's not just a terminological question because there's a clear definition of what a method is in Python and it even has a distinct data type, apart from a function.

2017-06-06 23:08 UTC, aqrln commented on Python/8-self.py
> +kiev = {
I don't think the example with a dictionary conveys anything useful, that's not how you would write code in Python. I'd rather show how one would invoke unbound and bound methods (or functions residing in the class namespace and methods, speaking in Python 3 terms).

2017-06-06 23:13 UTC, aqrln requested changes
The last two comments are pretty critical, so I'm leaving a visible mark here.

Other than that, mostly looks good, good job!

2025-02-26 16:25 UTC, closed without merging